=== fabiuccio/University/Software Engineering Project (Italian Language)/etc/hcs.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:simpleType name="positiveDouble">
	<xsd:restriction base="xsd:double">
		<xsd:minInclusive value="0.0" />
	</xsd:restriction>
</xsd:simpleType>

<xsd:simpleType name="positiveInteger">
	<xsd:restriction base="xsd:integer">
		<xsd:minInclusive value="0" />
	</xsd:restriction>
</xsd:simpleType>

<xsd:element name="hcs" >
	<xsd:complexType >
		<xsd:sequence>
		<xsd:element name="standard-temperatures" >
			<xsd:complexType >
				<xsd:attribute name="presence" type="positiveDouble" use="required" />
				<xsd:attribute name="away" type="positiveDouble" use="required" />
			</xsd:complexType>
		</xsd:element>
		<xsd:element name="standard-times" >
			<xsd:complexType>
				<xsd:attribute name="heating" type="positiveInteger" use="required" />
				<xsd:attribute name="away" type="positiveInteger" use="required" />
				<xsd:attribute name="inside" type="positiveInteger" use="required" />
			</xsd:complexType>
		</xsd:element>
		<xsd:element name="house" >
			<xsd:complexType>
				<xsd:sequence>
					<xsd:element name="room" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:attribute name="name" type="xsd:string" use="required" />
						<xsd:attribute name="sqm" type="xsd:integer" use="required" />
					</xsd:complexType>
					</xsd:element>
				</xsd:sequence>
			</xsd:complexType>
		</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>
</xsd:schema>

=== fabiuccio/University/Software Engineering Project (Italian Language)/etc/settings.xml
<?xml version="1.0"?>
<hcs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="hcs.xsd">
	<standard-temperatures presence="20.0" away="16.0" />
	<standard-times heating="8" away="4" inside="2" />
	<house>
		<room name="living room" sqm="40" />
		<room name="eating room" sqm="15" />
		<room name="sleeping room" sqm="15" />
		<room name="children room" sqm="20" />	
		<room name="visitors room" sqm="15" />	
		<room name="work room" sqm="10" />
		<room name="kitchen" sqm="15" />
		<room name="bathroom" sqm="5"/>
		<room name="visitor bathroom" sqm="5" />
		<room name="hall" sqm="10" />
		<room name="music room" sqm="30" />
	</house>
</hcs>
